### PR TITLE
Mnch 1030 whatsapp list messages

### PR DESCRIPTION
**Pull request by Buhle79**
## Purpose
_Describe the problem or feature in addition to a link to the issues._

Allow multiple messages using list messages that can be accessed through API in stacks.

## Approach
_How does this change address the problem?_
Add new field that will have list of messages.

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

## Learning
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

#### Blog Posts
- [How to Pull Request](https://github.com/flexyford/pull-request) Github Repo with Learning focused Pull Request Template.

### CODE REVIEW

**Review by jerith — COMMENTED** [review]
We need some import/export tests for list items.

**Comment by Buhle79** [comment]
@jerith for relook please

**Review by jerith — COMMENTED** [review]
I'm happy with the tests, but I don't have the context to review the rest. I think @rudigiesler needs to do that.

**Review by fritzbrand — APPROVED** [review]
👍

**Pull request merged**
